final bankAccounts = [
    
    'BankIslami Pakistan Limited',
    'Bank of Punjab',
    'Bank of Khyber',
    'Deutsche Bank A.G',
    'Dubai Islamic Bank Pakistan Limited',
    'Faysal Bank Limited',
    'First Women Bank Limited',
    'Habib Bank Limited',
    'Habib Metropolitan Bank Limited',
    'JS Bank Limited',
    'MCB Bank Limited',
    'MCB Islamic Bank Limited',
    'Meezan Bank Limited',
    'National Bank of Pakistan',
    'Summit Bank Pakistan',
    'Standard Chartered Bank (Pakistan) Limited',
    'Sindh Bank',
    'United Bank Limited',
    'Zarai Taraqiati Bank Limited',
    'Bank of Azad Jammu & Kashmir',
    'NayaPay',
    'SadaPay',
    'EasyPaisa',
    'Zindigi',
    'Samba Bank',
    'Soneri Bank',
    'Citi',
    'ICBC',
    'JazzCash',
  ];
